### ISSUE TITLE
Exporting an ArrayList only exports first page

### ISSUE THREAD

**Issue by MLindenhofer** [Level51/silverstripe-excel-export#5]
I have a report that generates an ArrayList. When exporting to Excel it only exports the very first page of the pagination. 

The csv-export-button removes the Pagination component for this reason.

```
 //Remove GridFieldPaginator as we're going to export the entire list.
        $gridField->getConfig()->removeComponentsByType(GridFieldPaginator::class);
```

**Comment by dkliemsch** [comment]
Hi Marimchen, thanks für the PR! I've just released a new version 1.0.1 containing the update.
